
site_name: DataFrames.jl
site_description: package for working with tabular data in Julia
repo_url: https://github.com/JuliaStats/DataFrames.jl

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- [index.md, Introduction]
- [man/getting_started.md, User guide, Getting Started]
- [man/io.md, User guide, IO]
- [man/joins.md, User guide, Joins]
- [man/split_apply_combine.md, User guide, Split-apply-combine]
- [man/reshaping_and_pivoting.md, User guide, Reshaping]
- [man/sorting.md, User guide, Sorting]
- [man/formulas.md, User guide, Formulas]
- [man/pooling.md, User guide, Pooling]
- [man/querying_frameworks.md, User guide, Querying frameworks]
- [lib/maintypes.md, API, Main types]
- [lib/utilities.md, API, Utilities]
- [lib/manipulation.md, API, Data manipulation]
- [NEWS.md, About, Release notes]
- [LICENSE.md, About, License]

