language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("BinDeps")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())';
